import '../models/bike.dart';
import '../models/pass_plan.dart';
import '../models/station.dart';
import '../models/user.dart';

class MockDataService {
  static List<PassPlan> getPassPlans() {
    return const [
      PassPlan(
        id: 'single-ride',
        name: 'Single Ride',
        priceUsd: 3.50,
        billingCycle: 'One-time',
        includedRideMinutes: 30,
        unlockFeeUsd: 0,
        overagePer30MinUsd: 2.00,
        autoRenew: false,
        description: 'For occasional trips with no subscription commitment.',
      ),
      PassPlan(
        id: 'day-pass',
        name: 'Day Pass',
        priceUsd: 11.99,
        billingCycle: '24 hours',
        includedRideMinutes: 45,
        unlockFeeUsd: 0,
        overagePer30MinUsd: 2.00,
        autoRenew: false,
        description: 'Unlimited rides for one day, up to 45 minutes each ride.',
      ),
      PassPlan(
        id: 'weekly-flex',
        name: 'Weekly Flex',
        priceUsd: 24.99,
        billingCycle: 'Weekly',
        includedRideMinutes: 45,
        unlockFeeUsd: 0,
        overagePer30MinUsd: 1.50,
        autoRenew: true,
        description: 'Balanced plan for tourists and short-term commuters.',
      ),
      PassPlan(
        id: 'monthly-commuter',
        name: 'Monthly Commuter',
        priceUsd: 59.99,
        billingCycle: 'Monthly',
        includedRideMinutes: 60,
        unlockFeeUsd: 0,
        overagePer30MinUsd: 1.00,
        autoRenew: true,
        description: 'Best value for frequent city riders and daily commuting.',
      ),
      PassPlan(
        id: 'annual-member',
        name: 'Annual Member',
        priceUsd: 499.00,
        billingCycle: 'Yearly',
        includedRideMinutes: 60,
        unlockFeeUsd: 0,
        overagePer30MinUsd: 0.75,
        autoRenew: true,
        description: 'Lowest long-term cost per month for regular riders.',
      ),
      PassPlan(
        id: 'student-monthly',
        name: 'Student Monthly',
        priceUsd: 39.99,
        billingCycle: 'Monthly',
        includedRideMinutes: 45,
        unlockFeeUsd: 0,
        overagePer30MinUsd: 1.00,
        autoRenew: true,
        description: 'Discounted commuter plan for verified students.',
        requiresVerification: true,
      ),
      PassPlan(
        id: 'business-team',
        name: 'Business Team Pass',
        priceUsd: 79.99,
        billingCycle: 'Monthly',
        includedRideMinutes: 60,
        unlockFeeUsd: 0,
        overagePer30MinUsd: 0.90,
        autoRenew: true,
        description: 'Corporate-focused plan with flexible commuting benefits.',
      ),
    ];
  }

  static List<Station> getStations() {
    return const [
      Station(
        id: 'st1',
        name: 'Central Park Hub',
        address: '12 Green Ave, Downtown',
        latitude: 37.7749,
        longitude: -122.4194,
        totalSlots: 20,
        availableBikes: 12,
        slots: [
          BikeSlotModel(index: 1, status: BikeSlotStatus.available),
          BikeSlotModel(index: 2, status: BikeSlotStatus.available),
          BikeSlotModel(index: 3, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 4, status: BikeSlotStatus.available),
          BikeSlotModel(index: 5, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 6, status: BikeSlotStatus.available),
          BikeSlotModel(index: 7, status: BikeSlotStatus.available),
          BikeSlotModel(index: 8, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 9, status: BikeSlotStatus.available),
          BikeSlotModel(index: 10, status: BikeSlotStatus.available),
          BikeSlotModel(index: 11, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 12, status: BikeSlotStatus.available),
          BikeSlotModel(index: 13, status: BikeSlotStatus.available),
          BikeSlotModel(index: 14, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 15, status: BikeSlotStatus.available),
          BikeSlotModel(index: 16, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 17, status: BikeSlotStatus.available),
          BikeSlotModel(index: 18, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 19, status: BikeSlotStatus.available),
          BikeSlotModel(index: 20, status: BikeSlotStatus.empty),
        ],
      ),
      Station(
        id: 'st2',
        name: 'Riverfront Station',
        address: '58 Harbor Lane, Midtown',
        latitude: 37.7781,
        longitude: -122.4142,
        totalSlots: 16,
        availableBikes: 9,
        slots: [
          BikeSlotModel(index: 1, status: BikeSlotStatus.available),
          BikeSlotModel(index: 2, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 3, status: BikeSlotStatus.available),
          BikeSlotModel(index: 4, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 5, status: BikeSlotStatus.available),
          BikeSlotModel(index: 6, status: BikeSlotStatus.available),
          BikeSlotModel(index: 7, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 8, status: BikeSlotStatus.available),
          BikeSlotModel(index: 9, status: BikeSlotStatus.available),
          BikeSlotModel(index: 10, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 11, status: BikeSlotStatus.available),
          BikeSlotModel(index: 12, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 13, status: BikeSlotStatus.available),
          BikeSlotModel(index: 14, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 15, status: BikeSlotStatus.available),
          BikeSlotModel(index: 16, status: BikeSlotStatus.empty),
        ],
      ),
      Station(
        id: 'st3',
        name: 'Campus Exchange',
        address: '201 College St, Uptown',
        latitude: 37.7707,
        longitude: -122.4264,
        totalSlots: 12,
        availableBikes: 5,
        slots: [
          BikeSlotModel(index: 1, status: BikeSlotStatus.available),
          BikeSlotModel(index: 2, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 3, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 4, status: BikeSlotStatus.available),
          BikeSlotModel(index: 5, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 6, status: BikeSlotStatus.available),
          BikeSlotModel(index: 7, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 8, status: BikeSlotStatus.available),
          BikeSlotModel(index: 9, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 10, status: BikeSlotStatus.available),
          BikeSlotModel(index: 11, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 12, status: BikeSlotStatus.empty),
        ],
      ),
      Station(
        id: 'st4',
        name: 'Sunset Market Stop',
        address: '77 Sunset Blvd, West End',
        latitude: 37.7689,
        longitude: -122.4317,
        totalSlots: 14,
        availableBikes: 7,
        slots: [
          BikeSlotModel(index: 1, status: BikeSlotStatus.available),
          BikeSlotModel(index: 2, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 3, status: BikeSlotStatus.available),
          BikeSlotModel(index: 4, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 5, status: BikeSlotStatus.available),
          BikeSlotModel(index: 6, status: BikeSlotStatus.available),
          BikeSlotModel(index: 7, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 8, status: BikeSlotStatus.available),
          BikeSlotModel(index: 9, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 10, status: BikeSlotStatus.available),
          BikeSlotModel(index: 11, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 12, status: BikeSlotStatus.available),
          BikeSlotModel(index: 13, status: BikeSlotStatus.empty),
          BikeSlotModel(index: 14, status: BikeSlotStatus.available),
        ],
      ),
    ];
  }

  static UrbanUser getUser() {
    return const UrbanUser(
      name: 'Ronan Miller',
      avatarUrl: '',
      totalDistanceKm: 142.6,
      totalRides: 39,
      co2SavedKg: 31.4,
      activePass: 'Monthly Commuter',
      recentTrips: [
        RecentTrip(
          routeName: 'Central Park to Riverfront',
          date: 'Apr 07, 2026',
          distanceKm: 4.2,
          cost: 2.5,
        ),
        RecentTrip(
          routeName: 'University Loop',
          date: 'Apr 05, 2026',
          distanceKm: 7.8,
          cost: 9.99,
        ),
        RecentTrip(
          routeName: 'Sunset District Ride',
          date: 'Apr 02, 2026',
          distanceKm: 3.4,
          cost: 2.5,
        ),
      ],
    );
  }
}
